### PR TITLE
Enable support for notifications and inverted blacklist (AKA Whitelist)

### PR DESCRIPTION
**Pull request by 0xDREAMS**

### CODE REVIEW

**Comment by 0xDREAMS** [comment]
@adamk33n3r @Bullish53 

Could I get some feed back on these code changes?

**Comment by adamk33n3r** [comment]
> @adamk33n3r @Bullish53
> 
> Could I get some feedback on these code changes?

Looks good to me, though I don't have write permissions on this repo and idk how active the owner is.

In the meantime, my plugin had finally been merged in. It's sole purpose is to create custom alerts, and it supports TTS. https://runelite.net/plugin-hub/show/watchdog

**Comment by 0xDREAMS** [comment]
Yooo I think this is literally everything I wanted from this plugin. Many thanks dude I'll check it out.

**Comment by adamk33n3r** [comment]
Ya for sure. The plugin is currently pretty barebones but I'd love to flesh it out more. So if you have any ideas or issues, feel free to log an issue on Github. (I think the stat drain one is a little over zealous)

**Pull request merged**
